#  docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 --volume qm1data:/mnt/mqm --publish 1414:1414 --publish 9443:9443 --detach --env MQ_APP_PASSWORD=passw0rd --name QM1 icr.io/ibm-messaging/mq:latest

version: '2'
services:
  mq:
    image: icr.io/ibm-messaging/mq:latest
    #image: ibmcom/mq
    privileged: true
    ports:
      - 1414:1414
      - 9443:9443
    environment:
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      LICENSE: accept
#    volumes:
#      - ./qm1data:/mnt/mqm